### PR TITLE
Add gej_equiv jets

### PR DESCRIPTION
**Pull request by roconnor-blockstream**

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
As usual, technically only the C code requires review.  You may wish to run it through CI first to make sure it passes.

**Review by apoelstra — APPROVED** [review]
ACK 80ca3089a69e23c19956498f315c67c3ea4b4932

**Comment by roconnor-blockstream** [comment]
rebased

**Review by apoelstra — APPROVED** [review]
ACK 9a16b7f2939fc7e6751eddb8158ac9318e231f45

**Pull request merged**
