### PR TITLE
Add fake benchmarks for OuputIsFee

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
This allows GenRustJets to run.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you update the committed autogenerated C source files?

**Comment by roconnor-blockstream** [comment]
Fixed.

**Review by apoelstra — APPROVED** [review]
ACK 32bfd7107918eca78ad6ca72d890a5a1cf507bcc

**Comment by sanket1729** [comment]
ACK

**Review by sanket1729 — APPROVED** [review]

**Pull request merged**
