### PR TITLE
Valgrind

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
This PR adds two features.

One is an option to ignore the results of the timing tests.  It can be disabled in nix builds by setting the `withTiming` argument to `false`.

The second feature is an option to run `valgrind` on the test suite in the `CheckPhase`.  This can be enabled in nix builds by setting the `withValgrind` argument to `true`.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
@apoelstra for your CI, I expect you will want to set the `withTiming` argument to `false` to remove the flaky timing tests.  And you will want to add `withValgrind` to your extensive testing.  This can be added in combination with the other extensive tests; there is no need to run every combination.

**Comment by roconnor-blockstream** [comment]
Fixes #202

**Review by uncomputable — APPROVED** [review]
ACK ec3b1ff4c0bfc8051c6a2d9f90f27fdf63367fd9 Looks good and runs on my end

**Comment by apoelstra** [comment]
```
==304== 
==304== HEAP SUMMARY:
==304==     in use at exit: 72 bytes in 1 blocks
==304==   total heap usage: 209 allocs, 208 frees, 4,602,157 bytes allocated
==304== 
==304== LEAK SUMMARY:
==304==    definitely lost: 0 bytes in 0 blocks
==304==    indirectly lost: 0 bytes in 0 blocks
==304==      possibly lost: 0 bytes in 0 blocks
==304==    still reachable: 72 bytes in 1 blocks
==304==         suppressed: 0 bytes in 0 blocks
==304== Reachable blocks (those to which a pointer was found) are not shown.
==304== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==304== 
==304== For lists of detected and suppressed errors, rerun with: -s
```

when running the regression tests

**Comment by apoelstra** [comment]
Also
```
==304== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==304== Command: ./test --no-timing
==304== 
==304== Syscall param write(buf) points to unaddressable byte(s)
==304==    at 0x497963D: syscall (in /nix/store/j6mwswpa6zqhdm1lm2lv9iix3arn774g-glibc-2.38-27/lib/libc.so.6)
==304==    by 0x4A5A009: mincore_validate (in /nix/store/g3r8b2n3v247d1wb5987nrcg3xh6wgda-libunwind-1.6.2/lib/libunwind.so.8.0.1)
==304==    by 0x4A59EF9: access_mem (in /nix/store/g3r8b2n3v247d1wb5987nrcg3xh6wgda-libunwind-1.6.2/lib/libunwind.so.8.0.1)
==304==    by 0x4A5E9AB: apply_reg_state (in /nix/store/g3r8b2n3v247d1wb5987nrcg3xh6wgda-libunwind-1.6.2/lib/libunwind.so.8.0.1)
==304==    by 0x4A5EFC6: _ULx86_64_dwarf_step (in /nix/store/g3r8b2n3v247d1wb5987nrcg3xh6wgda-libunwind-1.6.2/lib/libunwind.so.8.0.1)
==304==    by 0x4A5AE86: _ULx86_64_step (in /nix/store/g3r8b2n3v247d1wb5987nrcg3xh6wgda-libunwind-1.6.2/lib/libunwind.so.8.0.1)
==304==    by 0x48600DA: ??? (in /nix/store/xk83yxz3jllmp1m4v7n9pp2fkw2qdbsn-gperftools-2.10/lib/libprofiler.so.0.5.5)
==304==    by 0x485F5DF: ??? (in /nix/store/xk83yxz3jllmp1m4v7n9pp2fkw2qdbsn-gperftools-2.10/lib/libprofiler.so.0.5.5)
==304==    by 0x485CC21: ??? (in /nix/store/xk83yxz3jllmp1m4v7n9pp2fkw2qdbsn-gperftools-2.10/lib/libprofiler.so.0.5.5)
==304==    by 0x485CD24: ??? (in /nix/store/xk83yxz3jllmp1m4v7n9pp2fkw2qdbsn-gperftools-2.10/lib/libprofiler.so.0.5.5)
==304==    by 0x4004EBD: call_init (in /nix/store/j6mwswpa6zqhdm1lm2lv9iix3arn774g-glibc-2.38-27/lib/ld-linux-x86-64.so.2)
==304==    by 0x4004FAB: _dl_init (in /nix/store/j6mwswpa6zqhdm1lm2lv9iix3arn774g-glibc-2.38-27/lib/ld-linux-x86-64.so.2)
==304==  Address 0x1ffeffe000 is on thread 1's stack
==304==  504 bytes below stack pointer
```

**Comment by apoelstra** [comment]
Ok, cool, I'll disable the coverage+valgrind combination.

**Pull request merged**
