### PR TITLE
Pruning

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Haskell code for pruning jets.

Adds C example test cases for pruned and unpruned Simplicity programs.

### CODE REVIEW

**Comment by apoelstra** [comment]
Code looks good to me (at least, the C code). But I cannot build it -- I get the error

```
Preprocessing library 'Simplicity-Indef' for Simplicity-0.0.0..
Building library 'Simplicity-Indef' instantiated with
  Simplicity.Primitive = <Simplicity.Primitive>
for Simplicity-0.0.0..
[1 of 8] Compiling Simplicity.Primitive[sig] ( Haskell/Indef/Simplicity/Primitive.hsig, nothing )
[2 of 8] Compiling Simplicity.Term  ( Haskell/Indef/Simplicity/Term.hs, nothing )
[3 of 8] Compiling Simplicity.JetType ( Haskell/Indef/Simplicity/JetType.hs, nothing )
[4 of 8] Compiling Simplicity.Semantics ( Haskell/Indef/Simplicity/Semantics.hs, nothing )

Haskell/Indef/Simplicity/Semantics.hs:71:41: error:
    Variable not in scope:
      lift :: ReaderT PrimEnv Maybe b -> ReaderT PrimEnv Maybe b
    Suggested fix:
      Perhaps you want to add ‘lift’ to the import list in the import of
      ‘Control.Monad.Reader’
      (Haskell/Indef/Simplicity/Semantics.hs:14:1-41).
   |
71 |   optfs a | Just jt <- matcher =<< jm = lift . ReaderT $ flip (proxyImplementation fe jt) a
   |                                         ^^^^
```

which isn't even in our library, but I'm not sure what to do about it.

**Comment by apoelstra** [comment]
It's commit 5e4c132dbdf2010438aef34ce39202293d7c675e.

**Comment by roconnor-blockstream** [comment]
I think this might be my fault for not building intermediate commits.

**Comment by roconnor-blockstream** [comment]
Should be fixed now.

**Review by apoelstra — APPROVED** [review]
ACK 10e69f9d00b7a682a5cd5272186230d3a7898c55

**Pull request merged**
