### PR TITLE
Fix C headers

### PR DESCRIPTION
**Pull request by uncomputable**
I used a bash script to detect C headers with incomplete dependencies. We could add it to the repo if you want.

The script can be run inside `nix-shell --arg coq false --arg haskell false` from the project root.

```bash
compile_header() {
    # Relative header path without leading ./
    local header="${1#./}"
    
    echo "#include \"$header\"" > "tmp.c"

    if ! "$CC" -c "tmp.c" -I include -o /tmp/dummy_out; then
        exit 1
    fi
}

# Make `compile_header` available for `find`
export -f compile_header

cd C
# Compile each header and quit on the first failure
# Exclude secp256k1 directory
find . -path "./secp256k1" -prune -o -name "*.h" \( -exec bash -c 'compile_header "$0"' {} \; -o -quit \)
rm tmp.c
cd ..
```

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK ab86e5a55bcc80fd7af04bd522c5ed1df902bdeb

**Review by roconnor-blockstream — CHANGES_REQUESTED** [review]
LGTM.  Needs to be rebased.

**Comment by uncomputable** [comment]
Rebased

**Review by apoelstra — APPROVED** [review]
ACK f319952a8f2ae205889c713fd371b5fed38c7b9b

**Review by roconnor-blockstream — APPROVED** [review]
LGTM

**Pull request merged**
