### PR TITLE
Taptweak

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Add two new jets, a taptweak jet, and a tapdata jet.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
This PR is ready for review.  I've put it into draft state because we need to run the benchmarks on them, to assign them a cost.  Once that is done I'll amend this PR to add those costs, and adjust the CMRs appropriately.

I think @apoelstra will be doing the benchmarks??

While that is being done we can simultaneously run this PR through @apoelstra's CI and generally review the PR.

**Comment by apoelstra** [comment]
My benchmark computer will be busy for the next several hours (including running tests on this draft PR) but I will try to get these benchmarks run today.

**Review by apoelstra — COMMENTED** [review]
Successfully ran local tests on 8ae4c6b7a8420545377591eecdba881aec1835c2.

**Comment by apoelstra** [comment]
TapdataInit:
```
{
  "best_name": "unit_2",
  "best_value": 630.355508333529,
  "median_name": "unit_3",
  "median_value": 654.1267159364477,
  "worst_name": "unit_1",
  "worst_value": 654.8088901361084
}
```

BuildTapTweak:
```
{
  "best_name": "xo_pt_ge_offc_fe_outofrange_+_hi-bits_0",
  "best_value": 723.1729932177461,
  "median_name": "xo_pt_ge_offc_fe_lo-bits_+_lo-bits_4",
  "median_value": 29087.074000000004,
  "worst_name": "xo_pt_ge_oncurve_+_lo-bits_4",
  "worst_value": 51562.63
}
```

I sent the full data to you in another channel in case you want to sanity-check the overall results.

**Comment by roconnor-blockstream** [comment]
I've incorporated the benchmarks.

**Review by apoelstra — APPROVED** [review]
ACK 12c43d92063f19a623bcce59a2665d8dacaec457 successfully ran local tests

**Pull request merged**
