### PR TITLE
Typo corrections

### PR DESCRIPTION
**Pull request by roconnor-blockstream**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 2d2969cb30438e4d40ed2cc4efb01836aa1d19fc

**Comment by apoelstra** [comment]
To test this trivial PR, I used a script which ran every nix derivation in the repo (except mysecp256k1.nix, which wanted a git directory that I wasn't sure what to give it) on every commit. All passed.

**Comment by roconnor-blockstream** [comment]
Did you check that running the Haskell code generated the checked in `precomputed.h` function?

**Comment by apoelstra** [comment]
No, and I see that precomputed.h (among others) has been changed by this PR. Let me get that going and re-ACK.

**Review by apoelstra — APPROVED** [review]
ACK 2d2969cb30438e4d40ed2cc4efb01836aa1d19fc

**Pull request merged**
