### PR TITLE
Remove obsolete libsecp256k1 bindings

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Replaced by #34.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
Fixes #64.

**Comment by roconnor-blockstream** [comment]
@apoelstra You don't have to review this, but you may wish to run it through your CI.

**Comment by apoelstra** [comment]
Sure. Verified that this is a delete-only commit. Will post an ACK once my local CI finishes.

**Review by apoelstra — APPROVED** [review]
ACK 38a7c68690169db7b92557a760b253a1e32236ba

**Pull request merged**
