### PR TITLE
Update to vst 2.14

### PR DESCRIPTION
**Pull request by roconnor-blockstream**

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
If @uncomputable has the time, it would be helpful to validate the non-nix build instructions still work; however it isn't critical.

**Review by apoelstra — APPROVED** [review]
ACK 757ec1845f2b310f1b20843749be45a18e40fc97; successfully ran local tests

**Comment by uncomputable** [comment]
I will check the non-nix build.

**Comment by uncomputable** [comment]
`opam update` might need to be run for the latest Coq version to be recognized. (Still running the rest)

**Review by uncomputable — APPROVED** [review]
ACK 757ec1845f2b310f1b20843749be45a18e40fc97 Non-nix instructions successfully build Coq project

**Comment by roconnor-blockstream** [comment]
rebased

**Review by apoelstra — APPROVED** [review]
ACK 7d8de5051b646531364b62f12096d6b16c91d3d8; successfully ran local tests

**Pull request merged**
