### PR TITLE
GenRustJets: add FromStr and Display impl for jet enums

### PR DESCRIPTION
**Pull request by apoelstra**
I would like to be able to round-trip these jets with a nice string serialization. The snake-case version of the names will do well.

### CODE REVIEW

**Comment by apoelstra** [comment]
Tested with rust-simplicity to confirm that the resultring code compiles (after adding a new error variant and removing the existing Display impl which forwards to Debug).

**Comment by roconnor-blockstream** [comment]
While I admit that the existing code is not up to to par, I do suggest the following implementation as better:

``` 
rustJetDisplay :: Module -> Doc a
rustJetDisplay mod =
  "impl fmt::Display for" <+> pretty modname <+>
    nestBraces ("fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result" <+>
      nestBraces ("match self" <+>
        nestBraces (vsep (
          map (<>comma)
            [ pretty modname <> "::" <> pretty (jetName jet) <+> "=> f.write_str" <> (parens . dquotes . pretty $ cJetName jet)
            | SomeArrow jet <- moduleJets mod
            ]))
      )
    )
 where
  modname = rustModuleName mod

rustJetFromStr :: Module -> Doc a
rustJetFromStr mod =
  "impl str::FromStr for" <+> pretty modname <+>
    nestBraces (vsep
    [ "type Err = Error;"
    , mempty
    , ("fn from_str(s: &str) -> Result<Self, Error>" <+>
        nestBraces ("match s" <+>
          nestBraces (vsep (
            map (<> comma)
              ([ dquotes (pretty (cJetName jet)) <+> "=> Ok" <> parens (pretty modname <> "::" <> pretty (jetName jet))
               | SomeArrow jet <- moduleJets mod
               ] ++ [ "x => Err(Error::InvalidJetName(x.to_owned()))" ]
              )))
      ))
    ])
 where
  modname = rustModuleName mod
```

With

    import Prettyprinter ( Doc, (<+>), braces, comma, dquotes, fillSep, line, nest, parens, pretty, punctuate, semi, tupled, vsep

**Comment by apoelstra** [comment]
Thanks! That looks way better.

**Comment by apoelstra** [comment]
@roconnor-blockstream ok force-pushed to use your code

**Pull request merged**
