### PR TITLE
Valgrind the Haskell FFI testsuite

### PR DESCRIPTION
**Pull request by roconnor-blockstream**

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
@apoelstra you will want to add `--arg withValgrind true` to one of your CI entries for building Haskell.  It runs pretty slow, so I would only do it in one configuration.

**Comment by roconnor-blockstream** [comment]
Fixes #124

**Review by apoelstra — APPROVED** [review]
ACK 0b7b0e82438dd624abce7e64470765ad9c94cadd; successfully ran local tests

**Review by uncomputable — APPROVED** [review]
ACK 0b7b0e82438dd624abce7e64470765ad9c94cadd `nix-build -A haskell --arg withValgrind true` runs without problem (I quit the tests after the first dozen jets passed)

**Comment by roconnor-blockstream** [comment]
@apoelstra Can you ACK that you integrated this mode of evaluation into your CI process for one configuration?

**Pull request merged**
