### PR TITLE
Rename tapbranch to tappath

### LINKED ISSUE #116: Rename Tapbranch to Tappath
> (I think it's better to call it the path to the leaf, as "tapbranch" seems more to refer to each splitting step in the tree) -- AJ

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Tapbranch is more appropriate for a single branch point. So instead we use tappath for an entire path from root to leaf.

Fixes #116.

### CODE REVIEW

**Comment by apoelstra** [comment]
```
Haskell/cbits/elements/env.c: In function ‘c_set_rawTapEnv’:

Haskell/cbits/elements/env.c:61:57: error:
     error: ‘rawTapEnv’ has no member named ‘branchLen’
       61 |   *result = (rawTapEnv){ .controlBlock = controlBlock, .branchLen = branchLen, .scriptCM>
          |                                                         ^~~~~~~~~
   |
61 |   *result = (rawTapEnv){ .controlBlock = controlBlock, .branchLen = branchLen, .scriptCMR = scr>
   |                                                         ^

Haskell/cbits/elements/env.c:61:69: error:
     warning: initialization of ‘const unsigned char *’ from ‘unsigned char’ makes pointer from inte>
       61 |   *result = (rawTapEnv){ .controlBlock = controlBlock, .branchLen = branchLen, .scriptCM>
          |                                                                     ^~~~~~~~~
   |
61 |   *result = (rawTapEnv){ .controlBlock = controlBlock, .branchLen = branchLen, .scriptCMR = scr>
   |                                                                     ^

```

**Comment by roconnor-blockstream** [comment]
Seems `cabal build` is not hermetic at least when it comes to FFI bindings.

**Comment by roconnor-blockstream** [comment]
Fixed.

**Review by apoelstra — APPROVED** [review]
ACK 5fe9d71bcba4407b42f2205a7114847e80d8e40e

**Pull request merged**
