### PR TITLE
Example Simplicity Program

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Generates data used to create example Elements transactions.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
I'll make an asciinema video illustrating how to make liquid testnet transactions with this little program.

**Comment by uncomputable** [comment]
This is a P2PK Simplicity program, right? I can run the executable locally, but I'm not sure what to do for `--final-script-witness`.

**Review by apoelstra — APPROVED** [review]
ACK 377d5344634ddb62cb4e7259c975ee55d61d609d; successfully ran local tests

**Review by uncomputable — APPROVED** [review]
ACK 377d5344634ddb62cb4e7259c975ee55d61d609d The code runs, but I was not able to make a transaction.

**Comment by roconnor-blockstream** [comment]
I've updated this PR to randomly tweak the internal key to illustrate privacy and avoiding address reuse, since I was the one advocating for this recently.

**Comment by roconnor-blockstream** [comment]
Also there is a video demo of this program at https://asciinema.org/a/zAPDGjb1RoxWgwW8oTvkfngib if you want to see in in action and/or try it yourself.  Though it is not a requirement of this review that you be able to successfully use this program, just if you want to try it.

**Review by apoelstra — APPROVED** [review]
ACK 335466927d97bbb0e1108904170993631380eb08; successfully ran local tests

**Comment by roconnor-blockstream** [comment]
@kiarafbickers video demo is in a comment above.

**Pull request merged**
